import csv
import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(ROOT_DIR, "data")
os.makedirs(DATA_DIR, exist_ok=True)

LABELED_DATA: list[tuple[str, str]] = [
    ("mending benerin jalan daripada bikin taman yang ga kepake", "negative"),
    ("uang rakyat habis buat proyek yang ga jelas manfaatnya", "negative"),
    ("sudah berapa kali dilaporkan tapi tidak ada tindakan sama sekali", "negative"),
    ("tiap hujan pasti banjir, entah kemana anggaran drainasenya", "negative"),
    ("lebih baik fokus ke jalan rusak dulu sebelum bikin proyek baru", "negative"),
    ("warga sudah capek nunggu janji perbaikan yang tidak pernah ditepati", "negative"),
    ("kalau begini terus kapan infrastrukturnya mau maju", "negative"),
    ("dana pembangunan besar tapi hasilnya tidak kelihatan", "negative"),
    ("proyek selesai tapi kualitasnya mengecewakan", "negative"),
    ("baru sebulan diperbaiki sudah rusak lagi", "negative"),
    ("mending anggarannya buat yang lebih penting", "negative"),
    ("sudah lama minta diperbaiki tapi tidak ada respons", "negative"),
    ("percuma dilaporkan kalau tidak ditindaklanjuti", "negative"),
    ("entah kemana laporan warga selama ini", "negative"),
    ("pembangunan asal jadi tanpa memperhatikan kualitas", "negative"),
    ("daripada bikin yang baru mending rawat yang sudah ada", "negative"),
    ("warga yang bayar pajak tapi tidak merasakan manfaatnya", "negative"),
    ("sudah bertahun-tahun begini tidak ada perubahan", "negative"),
    ("proyek mangkrak sudah lama tidak ada kelanjutannya", "negative"),
    ("lebih baik transparansi anggaran dulu baru bicara pembangunan", "negative"),

    ("jalan di depan rumah saya berlubang sangat dalam dan berbahaya", "negative"),
    ("drainase tersumbat sampah dan air meluap ke jalan setiap hujan", "negative"),
    ("lampu jalan sudah mati berbulan-bulan tidak ada yang memperbaiki", "negative"),
    ("jembatan di RW 03 retak dan sangat membahayakan pengendara", "negative"),
    ("trotoar rusak parah dan tidak bisa dipakai pejalan kaki", "negative"),
    ("got mampet dan bau busuk sudah sangat mengganggu warga sekitar", "negative"),
    ("taman kota tidak terawat rumput liar tumbuh dimana-mana", "negative"),
    ("pohon tumbang menutupi jalan dan belum dibersihkan berhari-hari", "negative"),
    ("jalan berlubang sudah menelan korban kecelakaan berkali-kali", "negative"),
    ("banjir rutin setiap tahun karena drainase tidak pernah dibenahi", "negative"),
    ("fasilitas umum vandal dan tidak ada yang memperbaiki", "negative"),
    ("halte bus rusak atapnya bocor tidak nyaman untuk penumpang", "negative"),
    ("jalan sempit tidak bisa dilalui dua kendaraan sekaligus", "negative"),
    ("sampah menumpuk di pinggir jalan sudah berhari-hari tidak diangkut", "negative"),
    ("saluran air meluber ke permukiman warga saat hujan deras", "negative"),
    ("penerangan jalan sangat minim berbahaya di malam hari", "negative"),
    ("jalan aspal mengelupas dan berbahaya untuk pengendara motor", "negative"),
    ("fasilitas taman untuk anak-anak sudah rusak dan tidak diganti", "negative"),
    ("got di depan komplek kami meluap setiap kali hujan lebat", "negative"),
    ("jembatan penghubung antar kampung sudah tidak layak pakai", "negative"),
    ("proyek galian jalan dibiarkan terbuka tanpa pagar pengaman", "negative"),
    ("material bangunan proyek menghalangi akses jalan warga", "negative"),
    ("pengerjaan jalan asal-asalan langsung rusak sebelum selesai", "negative"),
    ("tidak ada rambu lalu lintas di persimpangan yang rawan kecelakaan", "negative"),
    ("air PAM tidak mengalir sudah tiga hari tanpa pemberitahuan", "negative"),
    ("tong sampah di taman sudah penuh tapi tidak segera dikosongkan", "negative"),
    ("bahu jalan dipakai parkir liar karena tidak ada penertiban", "negative"),
    ("jalan protokol rusak parah padahal baru diperbaiki tahun lalu", "negative"),
    ("drainase baru dibangun tapi desainnya salah air malah menggenang", "negative"),
    ("kondisi jembatan sangat memprihatinkan perlu segera diperbaiki", "negative"),

    ("jalan di kelurahan kami akhirnya diperbaiki terima kasih pak lurah", "positive"),
    ("drainase baru berfungsi dengan baik banjir sudah tidak ada lagi", "positive"),
    ("lampu jalan baru dipasang warga merasa lebih aman di malam hari", "positive"),
    ("taman kota renovasi hasilnya bagus warga senang bisa rekreasi", "positive"),
    ("trotoar baru sangat nyaman untuk pejalan kaki dan ramah difabel", "positive"),
    ("pengerjaan jalan cepat dan hasilnya rapi memuaskan warga", "positive"),
    ("program penghijauan kota berhasil membuat lingkungan lebih sejuk", "positive"),
    ("jembatan baru kokoh dan lebar memperlancar arus lalu lintas", "positive"),
    ("perbaikan got membuat lingkungan lebih bersih dan tidak berbau", "positive"),
    ("respon pemerintah cepat laporan langsung ditindaklanjuti besoknya", "positive"),
    ("fasilitas olahraga di taman lengkap dan terawat dengan baik", "positive"),
    ("jalan baru mempersingkat waktu tempuh warga ke pusat kota", "positive"),
    ("sistem pengelolaan sampah baru berjalan lancar lingkungan bersih", "positive"),
    ("penerangan jalan ditingkatkan angka kejahatan berkurang signifikan", "positive"),
    ("proyek drainase selesai tepat waktu sesuai janji pemerintah", "positive"),
    ("kualitas aspal jalan baru sangat baik tidak mudah rusak", "positive"),
    ("taman bermain anak baru sangat disukai warga sekitar", "positive"),
    ("petugas kebersihan rajin dan lingkungan selalu terjaga kebersihannya", "positive"),
    ("jalan desa kami akhirnya diaspal setelah puluhan tahun menunggu", "positive"),
    ("pembangunan trotoar membuat warga lebih nyaman dan aman berjalan kaki", "positive"),
    ("got yang dulu mampet sekarang sudah lancar setelah diperbaiki", "positive"),
    ("halte bus baru dilengkapi kursi dan atap yang nyaman", "positive"),
    ("proyek jembatan dikerjakan dengan serius dan hasilnya memuaskan", "positive"),
    ("perbaikan jalan di kampung kami disambut antusias seluruh warga", "positive"),
    ("pemasangan rambu lalu lintas baru membuat jalan lebih tertib", "positive"),
    ("renovasi pasar berhasil meningkatkan kenyamanan pedagang dan pembeli", "positive"),
    ("sistem drainase baru berhasil mengatasi banjir yang selama ini rutin", "positive"),
    ("pengaspalan jalan gang sempit sangat membantu warga", "positive"),
    ("taman kota yang baru menjadi ruang publik favorit warga", "positive"),
    ("penerangan di jembatan baru membuat warga lebih aman melintas malam hari", "positive"),

    ("proyek perbaikan jalan dijadwalkan mulai minggu depan", "neutral"),
    ("pembangunan drainase di kelurahan sukajadi sedang berlangsung", "neutral"),
    ("anggaran infrastruktur kota tahun ini sebesar dua ratus miliar", "neutral"),
    ("pengerjaan jembatan diperkirakan selesai dalam tiga bulan", "neutral"),
    ("pemerintah kota mengadakan rapat koordinasi infrastruktur hari ini", "neutral"),
    ("proyek pemasangan lampu jalan mencakup lima kelurahan", "neutral"),
    ("dinas pekerjaan umum akan melakukan inspeksi jalan bulan depan", "neutral"),
    ("pembangunan taman kota memasuki tahap kedua", "neutral"),
    ("tender proyek drainase dijadwalkan bulan depan", "neutral"),
    ("perbaikan trotoar akan dilakukan secara bertahap di seluruh kecamatan", "neutral"),
    ("kapan jadwal perbaikan jalan di perumahan griya mas", "neutral"),
    ("berapa lama waktu yang dibutuhkan untuk perbaikan jembatan ini", "neutral"),
    ("siapa kontraktor yang mengerjakan proyek jalan di blok b", "neutral"),
    ("dimana lokasi pengerjaan drainase yang baru dimulai hari ini", "neutral"),
    ("proyek ini masih dalam tahap perencanaan dan kajian teknis", "neutral"),
    ("informasi lebih lanjut akan disampaikan pada pertemuan warga", "neutral"),
    ("pengumuman jadwal perbaikan jalan akan diinformasikan melalui rt setempat", "neutral"),
    ("proses pengadaan material sedang berlangsung", "neutral"),
    ("dokumen teknis proyek sedang dalam proses persetujuan", "neutral"),
    ("rencana pembangunan jembatan baru masih dalam tahap studi kelayakan", "neutral"),
    ("pemerintah mengalokasikan dana untuk perbaikan infrastruktur tahun depan", "neutral"),
    ("dinas tata kota mencatat ada lima puluh titik jalan rusak di kota ini", "neutral"),
    ("program perbaikan jalan akan dimulai setelah anggaran disetujui dewan", "neutral"),
    ("kontraktor sedang melakukan survei lokasi untuk proyek jalan baru", "neutral"),
    ("rapat pembahasan anggaran infrastruktur dijadwalkan kamis mendatang", "neutral"),
    ("perbaikan lampu jalan dilaporkan ke dinas terkait untuk ditindaklanjuti", "neutral"),
    ("warga diminta bersabar selama proses pembangunan berlangsung", "neutral"),
    ("proyek normalisasi sungai melibatkan beberapa instansi terkait", "neutral"),
    ("jadwal pengangkutan sampah di wilayah ini adalah setiap selasa dan jumat", "neutral"),
    ("pemerintah sedang mengevaluasi kondisi seluruh jembatan di kota", "neutral"),
    ("pembangunan infrastruktur kota berjalan sesuai rencana induk", "neutral"),
    ("koordinasi antar dinas diperlukan untuk penyelesaian proyek ini", "neutral"),
    ("warga dapat melaporkan kerusakan infrastruktur melalui aplikasi livon", "neutral"),
    ("tim teknis sedang melakukan assessment kerusakan jalan di wilayah utara", "neutral"),
    ("pengerjaan proyek drainase akan menyebabkan penutupan sebagian jalan", "neutral"),
    ("anggaran perbaikan jalan rusak sedang dalam proses pencairan", "neutral"),
    ("pemerintah kota menerima bantuan dana dari pusat untuk infrastruktur", "neutral"),
    ("pembangunan jalan baru akan menghubungkan dua kelurahan yang selama ini terisolasi", "neutral"),
    ("proyek revitalisasi taman kota ditargetkan selesai akhir tahun ini", "neutral"),
    ("dinas kebersihan menambah armada truk sampah untuk wilayah barat", "neutral"),

    ("katanya mau diperbaiki bulan lalu tapi sampai sekarang belum ada tanda-tanda", "negative"),
    ("sudah lapor berkali-kali tetap tidak ada tindakan nyata", "negative"),
    ("janji perbaikan jalan sudah sering disampaikan tapi realisasinya nol", "negative"),
    ("tidak habis pikir kenapa jalan yang sama terus rusak padahal baru diperbaiki", "negative"),
    ("warga kecil terus yang menanggung akibat infrastruktur yang tidak dirawat", "negative"),
    ("aneh jalan di perumahan elit mulus tapi di kampung kami berlubang terus", "negative"),
    ("sudah tiga periode kepala daerah masalah banjir ini tidak pernah selesai", "negative"),
    ("kontraktor asal kerja pengawasan dari pemerintah tidak ada", "negative"),
    ("proyek jalan selesai di atas kertas tapi kondisi aslinya masih rusak parah", "negative"),
    ("apakah perlu ada korban dulu baru jalan ini diperbaiki", "negative"),
    ("tidak ada transparansi sama sekali mengenai penggunaan anggaran infrastruktur", "negative"),
    ("pelaksanaan proyek tidak sesuai dengan spesifikasi teknis yang dijanjikan", "negative"),
    ("pengerjaan dilakukan tidak profesional dan asal-asalan", "negative"),
    ("banjir sudah setinggi lutut tapi tidak ada respons dari pemerintah daerah", "negative"),
    ("infrastruktur kota makin memburuk dari tahun ke tahun bukan malah membaik", "negative"),
    ("sayang sekali anggaran besar tapi kualitas pekerjaan sangat buruk", "negative"),
    ("entah sampai kapan warga harus bersabar dengan kondisi jalan seperti ini", "negative"),
    ("proyek dikerjakan terburu-buru menjelang akhir tahun anggaran hasilnya buruk", "negative"),
    ("sudah jatuh tertimpa tangga jalan rusak eh malah dikenakan retribusi", "negative"),
    ("tidak layak disebut kota modern kalau infrastruktur dasarnya saja tidak beres", "negative"),

    ("meskipun sempat terlambat akhirnya jalan di kampung kami selesai diperbaiki juga", "positive"),
    ("tidak menyangka respons pemerintah bisa secepat ini setelah laporan warga", "positive"),
    ("hasil pengerjaan jauh lebih bagus dari yang diharapkan warga", "positive"),
    ("untuk pertama kalinya warga melihat ada kemajuan nyata di infrastruktur kota", "positive"),
    ("apresiasi untuk petugas yang bekerja keras di tengah cuaca buruk", "positive"),
    ("akhirnya ada perubahan nyata bukan sekadar janji kampanye", "positive"),
    ("warga sangat berterima kasih atas perhatian pemerintah terhadap keluhan kami", "positive"),
    ("kualitas pengerjaan kali ini jauh lebih baik dari proyek sebelumnya", "positive"),
    ("proyek berjalan transparan warga bisa ikut memantau prosesnya", "positive"),
    ("luar biasa dalam sebulan jalan rusak yang bertahun-tahun dibiarkan akhirnya beres", "positive"),
    ("peningkatan kualitas infrastruktur berdampak positif bagi perekonomian warga", "positive"),
    ("program satu jalan satu kampung sangat membantu daerah terpencil", "positive"),
    ("penghargaan layak diberikan kepada tim yang menyelesaikan proyek tepat waktu", "positive"),
    ("senang sekali melihat taman kota kembali hidup dan ramai dikunjungi warga", "positive"),
    ("normalisasi sungai berhasil dan banjir tahunan akhirnya bisa diatasi", "positive"),

    ("mohon informasi kapan perbaikan jalan di rt 05 rw 02 akan dilaksanakan", "neutral"),
    ("apakah ada rencana pemasangan lampu jalan di gang melati", "neutral"),
    ("bagaimana prosedur pelaporan kerusakan infrastruktur kepada dinas terkait", "neutral"),
    ("berapa estimasi biaya perbaikan drainase sepanjang jalan sudirman", "neutral"),
    ("siapa yang bertanggung jawab atas pemeliharaan taman kota", "neutral"),
    ("apakah proyek normalisasi sungai cikapundung sudah ada jadwalnya", "neutral"),
    ("kami ingin mengetahui perkembangan proyek jembatan yang sedang dikerjakan", "neutral"),
    ("tolong informasikan jadwal pengangkutan sampah yang baru di wilayah kami", "neutral"),
    ("apakah ada perubahan rute selama pengerjaan jalan berlangsung", "neutral"),
    ("kami membutuhkan informasi mengenai spesifikasi teknis proyek drainase ini", "neutral"),
    ("pihak kontraktor menyampaikan bahwa pengerjaan membutuhkan waktu dua minggu", "neutral"),
    ("dinas pekerjaan umum sedang mendata seluruh infrastruktur yang perlu diperbaiki", "neutral"),
    ("hasil inspeksi jembatan akan disampaikan kepada dewan kota pekan depan", "neutral"),
    ("laporan kerusakan jalan telah diterima dan sedang diproses", "neutral"),
    ("pemkot mengadakan sosialisasi rencana pembangunan infrastruktur kepada warga", "neutral"),
    ("tim survei akan turun ke lapangan untuk mengecek kondisi jalan yang dilaporkan", "neutral"),
    ("proses lelang proyek perbaikan jalan sedang berjalan sesuai prosedur", "neutral"),
    ("warga diimbau untuk berhati-hati melewati jalan yang sedang dalam perbaikan", "neutral"),
    ("pihak terkait akan segera menindaklanjuti laporan kerusakan yang masuk", "neutral"),
    ("pembangunan infrastruktur merupakan prioritas utama program kerja tahun ini", "neutral"),
]


def main() -> None:
    output_path = os.path.join(DATA_DIR, "domain_specific.csv")

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["texts", "labels"])
        writer.writerows(LABELED_DATA)

    from collections import Counter
    label_counts = Counter(label for _, label in LABELED_DATA)
    total = len(LABELED_DATA)

    print(f"saved {total} samples → {output_path}")
    print("\nlabel distribution:")
    for label, count in sorted(label_counts.items()):
        print(f"  {label:>10}: {count:>4} ({count/total*100:.1f}%)")
    print("\n⚠️  validate manually before using for training!")


if __name__ == "__main__":
    main()
