import { NextRequest } from "next/server";
import prisma from "@/lib/prisma";
import { DonationStatus } from "@/generated/prisma/enums";
import { internalError, notFound, ok } from "@/lib/api-response";

/**
 * @swagger
 * /api/donations/webhook:
 *   post:
 *     summary: Midtrans Webhook Callback
 *     description: Secret endpoint called automatically by Midtrans backend upon payment state changes (capture, settlement, expire, cancel, or deny). It updates the status of the donation and triggers funding updates on the relative project.
 *     tags:
 *       - Donations
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               order_id:
 *                 type: string
 *                 description: ID order generated by Livon's backend.
 *               transaction_status:
 *                 type: string
 *                 description: Status of the transaction from Midtrans (e.g. 'capture', 'settlement', 'cancel', 'deny', 'expire').
 *               transaction_id:
 *                 type: string
 *               payment_type:
 *                 type: string
 *     responses:
 *       200:
 *         description: Webhook processed successfully or acknowledged.
 *       404:
 *         description: Order Not Found. The provided order_id does not exist in the database.
 *       500:
 *         description: Webhook processing error. An internal server error occurred while updating states.
 */
export async function POST(req: NextRequest) {
  try {
    const body = await req.json();

    const {
      order_id,
      //   status_code,
      //   gross_amount,
      //   signature_key,
      transaction_status,
      transaction_id,
      payment_type,
    } = body;

    const donation = await prisma.donation.findUnique({
      where: { orderId: order_id },
      include: { project: true },
    });

    if (!donation?.orderId) {
      return notFound("Order Not Found");
    }

    if (donation.status === DonationStatus.SUCCESS) {
      return ok("Donation already processed");
    }

    if (
      transaction_status === "capture" ||
      transaction_status === "settlement"
    ) {
      const currentAmount = donation.project.currentFunding
        ? Number(donation.project.currentFunding)
        : 0;
      const addedAmount = Number(donation.amount);
      const newTotalFunding = currentAmount + addedAmount;

      await prisma.$transaction([
        prisma.donation.update({
          where: { orderId: order_id },
          data: {
            status: DonationStatus.SUCCESS,
            gatewayTransactionId: transaction_id,
            paymentMethod: payment_type,
            paidAt: new Date(),
          },
        }),

        prisma.project.update({
          where: { id: donation.projectId },
          data: {
            currentFunding: newTotalFunding,
          },
        }),
      ]);
    } else if (
      transaction_status === "cancel" ||
      transaction_status === "deny" ||
      transaction_status === "expire"
    ) {
      await prisma.donation.update({
        where: { orderId: order_id },
        data: {
          status: DonationStatus.FAILED,
          gatewayTransactionId: transaction_id,
          paymentMethod: payment_type,
        },
      });
    }

    return ok("Webhook acknowledged");
  } catch (error) {
    console.error(error);
    return internalError("Webhook processing error");
  }
}
